---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - list
  - patch
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - list
  - patch
  - watch
- apiGroups:
  - app.redhat.com
  resources:
  - visitorsapps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.redhat.com
  resources:
  - visitorsapps/finalizers
  verbs:
  - update
- apiGroups:
  - app.redhat.com
  resources:
  - visitorsapps/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - list
  - patch
  - watch
